### List all playlists
GET https://cse341-project-yrv7.onrender.com/playlists

###

### Get playlist by id
GET https://cse341-project-yrv7.onrender.com/playlists/67a43c103f04a11140235598

###

### Create a new playlist
# @name create_resource
POST https://cse341-project-yrv7.onrender.com/playlists HTTP/1.1
content-type: application/json

{
    "name":"Comedy Series - 2000-2010",
    "type":"series",
    "owner":"Glaucio"
}

###


### Updating the added resource
PUT https://cse341-project-yrv7.onrender.com/playlists/67a43c103f04a11140235598 HTTP/1.1
content-type: application/json

{
    "name":"Best Brazilian Movies - 2000-2020",
    "type":"movies",
    "owner":"Melissa"
}

### DELETE the added resource
DELETE https://cse341-project-yrv7.onrender.com/playlists/67a43c103f04a11140235598 HTTP/1.1