### List all movies
GET http://localhost:8080/movies

###

### Get movie by id
GET http://localhost:8080/movies/67a43b373f04a11140235597

###

### Create a new movie
# @name create_resource
POST http://localhost:8080/movies HTTP/1.1
content-type: application/json

{
    "name":"The Matrix",
}

###


### Updating the added resource
PUT http://localhost:8080/movies/67b17c587a4bd73a829458fa HTTP/1.1
content-type: application/json

{
    "name":"The Matrix 1",
}

### DELETE the added resource
DELETE http://localhost:8080/movies/67b17c587a4bd73a829458fa HTTP/1.1