### List all playlists
GET http://localhost:8080/playlists

###

### Get playlist by id
GET http://localhost:8080/playlists/67a440a73f04a11140235599

###

### Create a new playlist
# @name create_resource
POST http://localhost:8080/playlists HTTP/1.1
content-type: application/json

{
    "name":"Comedy Series - 2000-2010",
    "type":"series",
    "owner":"Glaucio"
}

###


### Updating the added resource
PUT http://localhost:8080/playlists/67b17c587a4bd73a829458fa HTTP/1.1
content-type: application/json

{
    "name":"Best Brazilian Movies - 2000-2020",
    "type":"movies",
    "owner":"Melissa"
}

### DELETE the added resource
DELETE http://localhost:8080/playlists/67a44181b1ec67af7b363fe4 HTTP/1.1


###

### Add a movie to a playlist
# @name create_resource
POST http://localhost:8080/playlists/67ba645dd4ec602e9fee000d/movies/67a43b373f04a11140235597 HTTP/1.1
content-type: application/json


###

### Remove a movie to a playlist
# @name create_resource
DELETE http://localhost:8080/playlists/67ba645dd4ec602e9fee000d/movies/67a43b373f04a11140235597 HTTP/1.1
content-type: application/json


###