### List all movies
GET http://localhost:8080/movies

###

### Get movie by id
GET http://localhost:8080/movies/67ba57848139fb27ccc4c9ba

###

### Create a new movie
# @name create_resource
POST http://localhost:8080/movies HTTP/1.1
content-type: application/json

{
  "Title": "Matrix",
  "Year": "1993",
  "Rated": "N/A",
  "Released": "01 Mar 1993",
  "Runtime": "60 min",
  "Genre": "Action, Drama, Fantasy",
  "Director": "N/A",
  "Writer": "Grenville Case",
  "Actors": "Nick Mancuso, Phillip Jarrett, Carrie-Anne Moss",
  "Plot": "Hitman Steven Matrix is shot, experiences afterlife, gets second chance by helping others. Wakes up, meets guides assigning cases where he aids people using unorthodox methods from past profession.",
  "Language": "English",
  "Country": "Canada",
  "Awards": "1 win total",
  "Poster": "https://m.media-amazon.com/images/M/MV5BM2JiZjU1NmQtNjg1Ni00NjA3LTk2MjMtNjYxMTgxODY0NjRhXkEyXkFqcGc@._V1_SX300.jpg",
  "Ratings": [
    {
      "Source": "Internet Movie Database",
      "Value": "7.2/10"
    }
  ],
  "Metascore": "N/A",
  "imdbRating": "7.2",
  "imdbVotes": "215",
  "imdbID": "tt0106062",
  "Type": "series",
  "totalSeasons": "N/A"
}

###


### Updating the added resource
PUT http://localhost:8080/movies/67ba57848139fb27ccc4c9ba HTTP/1.1
content-type: application/json

{
    "Title":"Matrix 1",
    "Year":"1992"
}

### DELETE the added resource
DELETE http://localhost:8080/movies/67ba57848139fb27ccc4c9ba HTTP/1.1